### ISSUE TITLE
Is the teacher model provided by CIFAR corrupted?

### ISSUE THREAD

**Issue by liuyyy111** [WangYZ1608/Knowledge-Distillation-via-ND#9]
I followed the steps in readme.md to train the model, but encountered the following error

`python3 train_cifar_kd.py --model_name resnet20_cifar  --teacher resnet56_cifar  --teacher_weights './ckpt/cifar_teachers.tar'  --dataset 'cifar100' --epoch 240 --batch_size 64 --lr 0.1 --cls_loss_factor 1.0 --kd_loss_factor 1.0 --nd_loss_factor 2.0 --save_dir "./run/CIFAR100/KD++/res56-res20"
`

> Traceback (most recent call last):
   File "train_cifar_kd.py", line 301, in <module>
     teacher_ckpt = torch.load(args.teacher_weights)['model']
   File "/home/sculiuyang/anaconda3/envs/distill/lib/python3.6/site-packages/torch/serialization.py", line 608, in load
     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
   File "/home/sculiuyang/anaconda3/envs/distill/lib/python3.6/site-packages/torch/serialization.py", line 762, in _legacy_load
     return legacy_load(f)
   File "/home/sculiuyang/anaconda3/envs/distill/lib/python3.6/site-packages/torch/serialization.py", line 687, in legacy_load
     tar.extract('storages', path=tmpdir)
   File "/home/sculiuyang/anaconda3/envs/distill/lib/python3.6/tarfile.py", line 2043, in extract
     tarinfo = self.getmember(member)
   File "/home/sculiuyang/anaconda3/envs/distill/lib/python3.6/tarfile.py", line 1754, in getmember
     raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

Does this mean the model is corrupted?

**Comment by WangYZ1608** [comment]
It seems like you have not untar cifar_teachers.tar, extracted the weights from the cifar_teachers.tar, and have a try.
